// MongoDB persistence for Syra.
//
// Loads a project's pages into the shape the agent expects and writes the
// resulting diff back into the `users.projects.$.pages` array, mirroring the
// validation used by /api/projects/[id]/pages.

import { ObjectId } from "mongodb"
import clientPromise from "@/lib/mongodb"
import type { FileChange } from "./types"

export interface LoadedProject {
  files: { path: string; content: string }[]
  exists: boolean
}

function isInvalidName(name: string): boolean {
  const decoded = (() => {
    try {
      return decodeURIComponent(name)
    } catch {
      return name
    }
  })()
  return (
    /^\.env(?:\.|$)/.test(decoded) ||
    /\/\.env(?:\.|$)/.test(decoded) ||
    decoded.includes("..") ||
    decoded.startsWith("/") ||
    decoded.startsWith("\\") ||
    decoded.includes("\0") ||
    /[<>:"|?*]/.test(decoded) ||
    decoded.length > 255
  )
}

export async function loadProjectFiles(userId: string, projectId: string): Promise<LoadedProject> {
  if (!ObjectId.isValid(projectId)) return { files: [], exists: false }
  const client = await clientPromise
  const db = client.db()
  const user = await db.collection("users").findOne({ id: userId }, { projection: { projects: 1 } })
  const project = user?.projects?.find((p: any) => p?._id?.toString() === projectId)
  if (!project) return { files: [], exists: false }
  const pages = Array.isArray(project.pages) ? project.pages : []
  return {
    exists: true,
    files: pages
      .filter((pg: any) => pg && typeof pg.name === "string")
      .map((pg: any) => ({ path: pg.name, content: typeof pg.content === "string" ? pg.content : "" })),
  }
}

export interface ApplyResult {
  saved: string[]
  removed: string[]
  skipped: { path: string; reason: string }[]
}

/** Persist a set of file changes to the project's pages array. */
export async function applyChanges(
  userId: string,
  projectId: string,
  changes: FileChange[],
  usedFor = "Generated by Syra",
): Promise<ApplyResult> {
  const result: ApplyResult = { saved: [], removed: [], skipped: [] }
  if (!ObjectId.isValid(projectId) || !changes.length) return result

  const client = await clientPromise
  const db = client.db()
  const oid = new ObjectId(projectId)

  for (const change of changes) {
    if (isInvalidName(change.path)) {
      result.skipped.push({ path: change.path, reason: "invalid or unsafe path" })
      continue
    }

    if (change.kind === "deleted") {
      await db.collection("users").updateOne(
        { id: userId, "projects._id": oid },
        { $pull: { "projects.$.pages": { name: change.path } } as any },
      )
      result.removed.push(change.path)
      continue
    }

    // created or modified -> upsert page
    const update = await db.collection("users").updateOne(
      {
        id: userId,
        projects: { $elemMatch: { _id: oid, "pages.name": change.path } },
      },
      {
        $set: {
          "projects.$[proj].pages.$[page].content": change.content,
          "projects.$[proj].pages.$[page].usedFor": usedFor,
          "projects.$[proj].pages.$[page].updatedAt": new Date(),
        },
      },
      {
        arrayFilters: [{ "proj._id": oid }, { "page.name": change.path }],
      },
    )

    if (update.matchedCount === 0) {
      await db.collection("users").updateOne(
        { id: userId, "projects._id": oid },
        {
          $push: {
            "projects.$.pages": {
              name: change.path,
              content: change.content,
              usedFor,
              createdAt: new Date(),
              updatedAt: new Date(),
            },
          } as any,
        },
      )
    }
    result.saved.push(change.path)
  }

  return result
}
