import { NextResponse } from "next/server";
import { NodeSSH } from "node-ssh";
import { getServerSession } from "next-auth/next";
import { authOptions } from "@/lib/auth";

export const runtime = "nodejs"

/**
 * POST /api/vps/restart
 * Restarts the Flask runner process on the VPS.
 * Body: { action: "start" | "stop" | "restart" }
 */
export async function POST(request: Request) {
  try {
    const session = await getServerSession(authOptions)
    if (session?.user?.email !== "dmarton336@gmail.com") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 })
    }

    const body = await request.json()
    const action = body.action || "restart"

    const host = process.env.VPS_IP
    const username = process.env.VPS_USERNAME
    const password = process.env.VPS_PASSWORD

    if (!host || !username || !password) {
      return NextResponse.json(
        { error: "VPS credentials not configured" },
        { status: 500 }
      )
    }

    const ssh = new NodeSSH()
    await ssh.connect({ host, username, password })

    const homeDir = username === "root" ? "/root" : `/home/${username}`
    const cwd = `${homeDir}/myapp`

    const run = async (cmd: string) => {
      const res = await ssh.execCommand(cmd, { cwd })
      return res
    }

    if (action === "stop" || action === "restart") {
      await run('pkill -f "python3.*/runner.py" || true')
      await run("fuser -k 5000/tcp || true")
      await new Promise((r) => setTimeout(r, 1000))
    }

    if (action === "start" || action === "restart") {
      // Verify runner.py exists
      const fileCheck = await run(`test -f ${cwd}/runner.py && echo "ok"`)
      if (!fileCheck.stdout.includes("ok")) {
        ssh.dispose()
        return NextResponse.json(
          { error: "runner.py not found on VPS. Run setup wizard first." },
          { status: 400 }
        )
      }

      // Update .env.server with latest Cloudflare & GitHub credentials so
      // the Flask server can auto-configure DNS records on deploy.
      const serverEnvVars: Record<string, string | undefined> = {
        CLOUDFLARE_API_KEY: process.env.CLOUDFLARE_API_KEY,
        CLOUDFLARE_ZONE_ID: process.env.CLOUDFLARE_ZONE_ID,
        GITHUB_API_TOKEN: process.env.GITHUB_API_TOKEN || process.env.GITHUB_TOKEN,
        GITHUB_OWNER: process.env.GITHUB_OWNER || process.env.GITHUB_USERNAME,
      }

      const envLines = Object.entries(serverEnvVars)
        .filter(([, v]) => v)
        .map(([k, v]) => `${k}=${v}`)

      if (envLines.length > 0) {
        const envContent = `# Auto-generated by Sycord VPS Restart\n${envLines.join("\n")}\n`
        await ssh.execCommand(`cat > .env.server`, { cwd, stdin: envContent })
      }

      await run(
        `nohup bash -c 'set -a; [ -f ${cwd}/.env.server ] && source ${cwd}/.env.server; set +a; exec python3 ${cwd}/runner.py' > ${cwd}/runner.log 2>&1 &`
      )

      // Wait for startup
      await new Promise((r) => setTimeout(r, 3000))

      const ps = await run('pgrep -f "python3.*/runner.py"')
      const running = !!ps.stdout.trim()

      if (!running) {
        const logTail = await run(`tail -n 30 ${cwd}/runner.log`)
        ssh.dispose()
        return NextResponse.json({
          success: false,
          error: `Runner failed to start.\n${logTail.stdout || logTail.stderr || "No log output."}`,
        })
      }

      // Also try to restart tunnel if config exists
      if (action === "restart") {
        await run('pkill -f "cloudflared tunnel" || true')
        await new Promise((r) => setTimeout(r, 500))
        const configExists = await run(`test -f ${cwd}/config.yml && echo "ok"`)
        if (configExists.stdout.includes("ok")) {
          await run(
            `nohup ${cwd}/cloudflared tunnel --config ${cwd}/config.yml run sycord-runner > ${cwd}/tunnel.log 2>&1 &`
          )
        }
      }
    }

    ssh.dispose()

    return NextResponse.json({
      success: true,
      message:
        action === "stop" ?"Runner stopped."
          : action === "start" ?"Runner started." :"Runner restarted.",
    })
  } catch (error: any) {
    console.error("[VPS Restart] Error:", error)
    return NextResponse.json(
      { error: error.message || "Failed to execute action" },
      { status: 500 }
    )
  }
}
